[package]
name = "pytqsm"
version = "0.6.1"
description = "Sentence segmenter that supports ~300 languages"
edition = "2021"

[lib]
name = "pytqsm"
crate-type = ["cdylib"]

[dependencies]
libtqsm = { path="../libtqsm" }
pyo3 = "0.19.0"
