use once_cell::sync::Lazy;
use std::collections::HashMap;

pub(crate) const LANGDATA_STR: &str = include_str!("data/langdata.json");
pub(crate) const QUOTE_PAIRS_ARRAY: [(&str, &str); 12] = [
    ("\"", "\""),
    (" '", "'"), // Need a space before ' to avoid capturing don't , l'Avv etc
    ("«", "»"),
    ("‘", "’"),
    ("‚", "‚"),
    ("“", "”"),
    ("‛", "‛"),
    ("„", "“"),
    ("‟", "‟"),
    ("‹", "›"),
    ("《", "》"),
    ("「", "」"),
];
pub(crate) const GLOBAL_SENTENCE_TERMINATORS: [char; 155] = [
    '\u{21}',
    '\u{2E}',
    '\u{3F}',
    '\u{589}',
    '\u{61D}',
    '\u{61E}',
    '\u{61F}',
    '\u{6D4}',
    '\u{700}',
    '\u{701}',
    '\u{702}',
    '\u{7F9}',
    '\u{837}',
    '\u{839}',
    '\u{83D}',
    '\u{83E}',
    '\u{964}',
    '\u{965}',
    '\u{104A}',
    '\u{104B}',
    '\u{1362}',
    '\u{1367}',
    '\u{1368}',
    '\u{166E}',
    '\u{1735}',
    '\u{1736}',
    '\u{1803}',
    '\u{1809}',
    '\u{1944}',
    '\u{1945}',
    '\u{1AA8}',
    '\u{1AA9}',
    '\u{1AAA}',
    '\u{1AAB}',
    '\u{1B5A}',
    '\u{1B5B}',
    '\u{1B5E}',
    '\u{1B5F}',
    '\u{1B7D}',
    '\u{1B7E}',
    '\u{1C3B}',
    '\u{1C3C}',
    '\u{1C7E}',
    '\u{1C7F}',
    '\u{2024}',
    '\u{203C}',
    '\u{203D}',
    '\u{2047}',
    '\u{2048}',
    '\u{2049}',
    '\u{2E2E}',
    '\u{2E3C}',
    '\u{2E53}',
    '\u{2E54}',
    '\u{A4FF}',
    '\u{A60E}',
    '\u{A60F}',
    '\u{A6F3}',
    '\u{A6F7}',
    '\u{A876}',
    '\u{A877}',
    '\u{A8CE}',
    '\u{A8CF}',
    '\u{A92F}',
    '\u{A9C8}',
    '\u{A9C9}',
    '\u{AA5D}',
    '\u{AA5E}',
    '\u{AA5F}',
    '\u{AAF0}',
    '\u{AAF1}',
    '\u{ABEB}',
    '\u{FE52}',
    '\u{FE56}',
    '\u{FE57}',
    '\u{FF01}',
    '\u{FF0E}',
    '\u{FF1F}',
    '\u{10A56}',
    '\u{10A57}',
    '\u{10F55}',
    '\u{10F56}',
    '\u{10F57}',
    '\u{10F58}',
    '\u{10F59}',
    '\u{10F86}',
    '\u{10F87}',
    '\u{10F88}',
    '\u{10F89}',
    '\u{11047}',
    '\u{11048}',
    '\u{110BE}',
    '\u{110BF}',
    '\u{110C0}',
    '\u{110C1}',
    '\u{11141}',
    '\u{11142}',
    '\u{11143}',
    '\u{111C5}',
    '\u{111C6}',
    '\u{111CD}',
    '\u{111DE}',
    '\u{111DF}',
    '\u{11238}',
    '\u{11239}',
    '\u{1123B}',
    '\u{1123C}',
    '\u{112A9}',
    '\u{1144B}',
    '\u{1144C}',
    '\u{115C2}',
    '\u{115C3}',
    '\u{115C9}',
    '\u{115CA}',
    '\u{115CB}',
    '\u{115CC}',
    '\u{115CD}',
    '\u{115CE}',
    '\u{115CF}',
    '\u{115D0}',
    '\u{115D1}',
    '\u{115D2}',
    '\u{115D3}',
    '\u{115D4}',
    '\u{115D5}',
    '\u{115D6}',
    '\u{115D7}',
    '\u{11641}',
    '\u{11642}',
    '\u{1173C}',
    '\u{1173D}',
    '\u{1173E}',
    '\u{11944}',
    '\u{11946}',
    '\u{11A42}',
    '\u{11A43}',
    '\u{11A9B}',
    '\u{11A9C}',
    '\u{11C41}',
    '\u{11C42}',
    '\u{11EF7}',
    '\u{11EF8}',
    '\u{11F43}',
    '\u{11F44}',
    '\u{16A6E}',
    '\u{16A6F}',
    '\u{16AF5}',
    '\u{16B37}',
    '\u{16B38}',
    '\u{16B44}',
    '\u{16E98}',
    '\u{1BC9F}',
    '\u{1DA88}',
    '\u{3002}',
    '\u{FF61}',
];
pub(crate) static LANGUAGE_FALLBACKS: Lazy<HashMap<&'static str, Vec<&'static str>>> =
    Lazy::new(|| {
        [
            ("ab", vec!["ru"]),
            ("abs", vec!["id"]),
            ("ace", vec!["id"]),
            ("ady", vec!["ady-cyrl"]),
            ("aeb", vec!["aeb-arab"]),
            ("aeb-arab", vec!["ar"]),
            ("aln", vec!["sq"]),
            ("alt", vec!["ru"]),
            ("ami", vec!["zh-hant"]),
            ("an", vec!["es"]),
            ("anp", vec!["hi"]),
            ("arn", vec!["es"]),
            ("arq", vec!["ar"]),
            ("ary", vec!["ar"]),
            ("arz", vec!["ar"]),
            ("ast", vec!["es"]),
            ("as", vec!["bn"]),
            ("atj", vec!["fr"]),
            ("av", vec!["ru"]),
            ("avk", vec!["fr", "es", "ru"]),
            ("awa", vec!["hi"]),
            ("ay", vec!["es"]),
            ("azb", vec!["fa"]),
            ("ba", vec!["ru"]),
            ("ban", vec!["id"]),
            ("ban-bali", vec!["ban"]),
            ("bar", vec!["de"]),
            ("bbc", vec!["bbc-latn"]),
            ("bbc-latn", vec!["id"]),
            ("bcc", vec!["fa"]),
            ("be-tarask", vec!["be"]),
            ("bgn", vec!["fa"]),
            ("bh", vec!["bho"]),
            ("bi", vec!["en"]),
            ("bjn", vec!["id"]),
            ("bm", vec!["fr"]),
            ("bpy", vec!["bn"]),
            ("bqi", vec!["fa"]),
            ("br", vec!["fr"]),
            ("btm", vec!["id"]),
            ("bug", vec!["id"]),
            ("bxr", vec!["ru"]),
            ("ca", vec!["oc"]),
            ("cbk-zam", vec!["es"]),
            ("cdo", vec!["nan", "zh-hant"]),
            ("ce", vec!["ru"]),
            ("co", vec!["it"]),
            ("crh", vec!["crh-latn"]),
            ("crh-cyrl", vec!["ru"]),
            ("cs", vec!["sk"]),
            ("csb", vec!["pl"]),
            ("cv", vec!["ru"]),
            ("de-at", vec!["de"]),
            ("de-ch", vec!["de"]),
            ("de-formal", vec!["de"]),
            ("dsb", vec!["de"]),
            ("dtp", vec!["ms"]),
            ("dty", vec!["ne"]),
            ("egl", vec!["it"]),
            ("eml", vec!["it"]),
            ("en-ca", vec!["en"]),
            ("en-gb", vec!["en"]),
            ("es-419", vec!["es"]),
            ("es-formal", vec!["es"]),
            ("ext", vec!["es"]),
            ("ff", vec!["fr"]),
            ("fit", vec!["fi"]),
            ("frc", vec!["fr"]),
            ("frp", vec!["fr"]),
            ("frr", vec!["de"]),
            ("fur", vec!["it"]),
            ("gag", vec!["tr"]),
            ("gan", vec!["gan-hant", "zh-hant", "zh-hans"]),
            ("gan-hans", vec!["zh-hans"]),
            ("gan-hant", vec!["zh-hant", "zh-hans"]),
            ("gcr", vec!["fr"]),
            ("gl", vec!["pt"]),
            ("glk", vec!["fa"]),
            ("gn", vec!["es"]),
            ("gom", vec!["gom-deva"]),
            ("gom-deva", vec!["hi"]),
            ("gor", vec!["id"]),
            ("gsw", vec!["de"]),
            ("guc", vec!["es"]),
            ("hak", vec!["zh-hant"]),
            ("hif", vec!["hif-latn"]),
            ("hrx", vec!["de"]),
            ("hsb", vec!["dsb", "de"]),
            ("ht", vec!["fr"]),
            ("hu-formal", vec!["hu"]),
            ("hyw", vec!["hy"]),
            ("ii", vec!["zh-cn", "zh-hans"]),
            ("inh", vec!["ru"]),
            ("io", vec!["eo"]),
            ("iu", vec!["ike-cans"]),
            ("jam", vec!["en"]),
            ("jut", vec!["da"]),
            ("jv", vec!["id"]),
            ("kaa", vec!["kk-latn", "kk-cyrl"]),
            ("kab", vec!["fr"]),
            ("kbd", vec!["kbd-cyrl"]),
            ("kbp", vec!["fr"]),
            ("khw", vec!["ur"]),
            ("kiu", vec!["tr"]),
            ("kjp", vec!["my"]),
            ("kk", vec!["kk-cyrl"]),
            ("kk-arab", vec!["kk-cyrl"]),
            ("kk-cn", vec!["kk-arab", "kk-cyrl"]),
            ("kk-kz", vec!["kk-cyrl"]),
            ("kk-latn", vec!["kk-cyrl"]),
            ("kk-tr", vec!["kk-latn", "kk-cyrl"]),
            ("kl", vec!["da"]),
            ("ko-kp", vec!["ko"]),
            ("koi", vec!["ru"]),
            ("krc", vec!["ru"]),
            ("krl", vec!["fi"]),
            ("ks", vec!["ks-arab"]),
            ("ksh", vec!["de"]),
            ("ku", vec!["ku-latn"]),
            ("ku-arab", vec!["ckb"]),
            ("kum", vec!["ru"]),
            ("kv", vec!["ru"]),
            ("lad", vec!["es"]),
            ("lb", vec!["de"]),
            ("lbe", vec!["ru"]),
            ("lez", vec!["ru", "az"]),
            ("li", vec!["nl"]),
            ("lij", vec!["it"]),
            ("liv", vec!["et"]),
            ("lki", vec!["fa"]),
            ("lld", vec!["it", "rm", "fur"]),
            ("lmo", vec!["pms", "eml", "lij", "vec", "it"]),
            ("ln", vec!["fr"]),
            ("lrc", vec!["fa"]),
            ("ltg", vec!["lv"]),
            ("luz", vec!["fa"]),
            ("lzh", vec!["zh-hant"]),
            ("lzz", vec!["tr"]),
            ("mad", vec!["id"]),
            ("mai", vec!["hi"]),
            ("map-bms", vec!["jv", "id"]),
            ("mdf", vec!["ru"]),
            ("mg", vec!["fr"]),
            ("mhr", vec!["ru"]),
            ("min", vec!["id"]),
            ("mnw", vec!["my"]),
            ("mo", vec!["ro"]),
            ("mrj", vec!["ru"]),
            ("ms-arab", vec!["ms"]),
            ("mwl", vec!["pt"]),
            ("myv", vec!["ru"]),
            ("mzn", vec!["fa"]),
            ("nah", vec!["es"]),
            ("nan", vec!["zh-hant"]),
            ("nap", vec!["it"]),
            ("nds", vec!["de"]),
            ("nds-nl", vec!["nl"]),
            ("nia", vec!["id"]),
            ("nl-informal", vec!["nl"]),
            ("nn", vec!["nb"]),
            ("nrm", vec!["fr"]),
            ("oc", vec!["ca", "fr"]),
            ("olo", vec!["fi"]),
            ("os", vec!["ru"]),
            ("pcd", vec!["fr"]),
            ("pdc", vec!["de"]),
            ("pdt", vec!["de"]),
            ("pfl", vec!["de"]),
            ("pih", vec!["en"]),
            ("pms", vec!["it"]),
            ("pnt", vec!["el"]),
            ("pt-br", vec!["pt"]),
            ("qu", vec!["es"]),
            ("qug", vec!["es"]),
            ("rgn", vec!["it"]),
            ("rmy", vec!["ro"]),
            ("roa-tara", vec!["it"]),
            ("rue", vec!["uk", "ru"]),
            ("rup", vec!["ro"]),
            ("ruq", vec!["ruq-latn", "ro"]),
            ("ruq-cyrl", vec!["mk"]),
            ("ruq-latn", vec!["ro"]),
            ("sa", vec!["hi"]),
            ("sah", vec!["ru"]),
            ("scn", vec!["it"]),
            ("sco", vec!["en"]),
            ("sdc", vec!["it"]),
            ("sdh", vec!["cbk", "fa"]),
            ("ses", vec!["fr"]),
            ("sg", vec!["fr"]),
            ("sgs", vec!["lt"]),
            ("sh", vec!["bs", "sr-el", "hr"]),
            ("shi", vec!["fr"]),
            ("shy", vec!["shy-latn"]),
            ("shy-latn", vec!["fr"]),
            ("sk", vec!["cs"]),
            ("skr", vec!["skr-arab"]),
            ("skr-arab", vec!["ur", "pnb"]),
            ("sli", vec!["de"]),
            ("smn", vec!["fi"]),
            ("sr", vec!["sr-ec"]),
            ("srn", vec!["nl"]),
            ("stq", vec!["de"]),
            ("sty", vec!["ru"]),
            ("su", vec!["id"]),
            ("szl", vec!["pl"]),
            ("szy", vec!["zh-tw", "zh-hant", "zh-hans"]),
            ("tay", vec!["zh-tw", "zh-hant", "zh-hans"]),
            ("tcy", vec!["kn"]),
            ("tet", vec!["pt"]),
            ("tg", vec!["tg-cyrl"]),
            ("trv", vec!["zh-tw", "zh-hant", "zh-hans"]),
            ("tt", vec!["tt-cyrl", "ru"]),
            ("tt-cyrl", vec!["ru"]),
            ("ty", vec!["fr"]),
            ("tyv", vec!["ru"]),
            ("udm", vec!["ru"]),
            ("ug", vec!["ug-arab"]),
            ("vec", vec!["it"]),
            ("vep", vec!["et"]),
            ("vls", vec!["nl"]),
            ("vmf", vec!["de"]),
            ("vot", vec!["fi"]),
            ("vro", vec!["et"]),
            ("wa", vec!["fr"]),
            ("wo", vec!["fr"]),
            ("wuu", vec!["zh-hans"]),
            ("xal", vec!["ru"]),
            ("xmf", vec!["ka"]),
            ("yi", vec!["he"]),
            ("za", vec!["zh-hans"]),
            ("zea", vec!["nl"]),
            ("zgh", vec!["kab"]),
            ("zh", vec!["zh-hans"]),
            ("zh-cn", vec!["zh-hans"]),
            ("zh-hant", vec!["zh-hans"]),
            ("zh-hk", vec!["zh-hant", "zh-hans"]),
            ("zh-mo", vec!["zh-hk", "zh-hant", "zh-hans"]),
            ("zh-my", vec!["zh-sg", "zh-hans"]),
            ("zh-sg", vec!["zh-hans"]),
            ("zh-tw", vec!["zh-hant", "zh-hans"]),
        ]
        .into_iter()
        .collect()
    });
