[package]
name = "tqsm"
version = "0.6.1"
description = "Sentence segmenter that supports ~300 languages"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
libtqsm = { path = "../libtqsm" }
